[package]
name = "fast-interceptor"
version = "0.1.0"
authors = ["WorksButNotTested"]
edition = "2018"
license = "MIT"
publish = false

[dependencies]
ainakan-gum = { path = "../../../ainakan-gum" }
lazy_static = "1.4"
ctor = "0.2"
libc = "0.2.126"
